create table public.zoning (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint zoning_pkey primary key (id)
) TABLESPACE pg_default;

create table public.boroughs (
  id bigint generated by default as identity not null,
  name text null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint boroughs_pkey primary key (id)
) TABLESPACE pg_default;

create table public.agricultural_zoning (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint agricultural_zoning_pkey primary key (id)
) TABLESPACE pg_default;

create table public.administratif_regions (
  region_id bigint not null,
  name text null,
  updated_at timestamp with time zone not null default now(),
  geom geometry null
) TABLESPACE pg_default;

create table public.fire_stations (
  fire_station_id integer not null,
  fire_station_no integer null,
  address text null,
  fire_service_names text null,
  updated_at timestamp not null default now(),
  geom geometry null,
  constraint fire_stations_pkey primary key (fire_station_id)
) TABLESPACE pg_default;

create table public.municipalities (
  municipality_code integer not null,
  municipality_name text null,
  address text null,
  city text null,
  postal_code text null,
  phone bigint null,
  email text null,
  website text null,
  population bigint null,
  updated_at timestamp not null default now(),
  geom geometry null,
  constraint municipalities_code_pkey primary key (municipality_code)
) TABLESPACE pg_default;

delete from public.zoning;