create table public.zoning (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint zoning_pkey primary key (id)
) TABLESPACE pg_default;

create table public.boroughs (
  id bigint generated by default as identity not null,
  name text null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint boroughs_pkey primary key (id)
) TABLESPACE pg_default;

create table public.agricultural_zoning (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint agricultural_zoning_pkey primary key (id)
) TABLESPACE pg_default;

create table public.administratif_regions (
  region_id bigint not null,
  name text null,
  updated_at timestamp with time zone not null default now(),
  geom geometry null,
  constraint administratif_regions_pkey primary key (region_id)
) TABLESPACE pg_default;



delete from public.zoning;