create table public.zoning (
  id bigint generated by default as identity not null,
  updated_at timestamp with time zone not null default now(),
  area real null,
  perimeter real null,
  geometry geometry null,
  constraint zoning_pkey primary key (id)
) TABLESPACE pg_default;

create table public.boroughs (
  id bigint generated by default as identity not null,
  name varchar null,
  updated_at timestamp with time zone not null default now(),

  area real null,
  perimeter real null,
  geometry geometry null,
  constraint boroughs_pkey primary key (id)
) TABLESPACE pg_default;



delete from public.zoning;