CREATE TABLE IF NOT EXISTS quebec_city_permits (
    id bigint generated by default as identity primary key,
    permit_number text,
    issue_date date,
    work_address text,
    domain text,
    affected_lots text,
    permit_type text,
    reason text,
    borough text,
    geometry geometry
)